const { DEPARTMENT_TYPES } = require("../constants/departmentTypes");
const { COMPLAINT_CATEGORIES } = require("../constants/complaintCategories");

const categoryDepartmentMap = {
  [COMPLAINT_CATEGORIES.ROAD]: DEPARTMENT_TYPES.ROAD_MAINTENANCE,
  [COMPLAINT_CATEGORIES.SANITATION]: DEPARTMENT_TYPES.SANITATION,
  [COMPLAINT_CATEGORIES.DRAINAGE]: DEPARTMENT_TYPES.DRAINAGE,
  [COMPLAINT_CATEGORIES.ELECTRICITY]: DEPARTMENT_TYPES.STREETLIGHT_ELECTRICITY,
  [COMPLAINT_CATEGORIES.WATER]: DEPARTMENT_TYPES.WATER_SUPPLY,
  [COMPLAINT_CATEGORIES.SAFETY]: DEPARTMENT_TYPES.PUBLIC_SAFETY,
  [COMPLAINT_CATEGORIES.ENVIRONMENT]: DEPARTMENT_TYPES.PARKS_ENVIRONMENT,
  [COMPLAINT_CATEGORIES.TRAFFIC]: DEPARTMENT_TYPES.TRAFFIC,
  [COMPLAINT_CATEGORIES.HEALTH]: DEPARTMENT_TYPES.HEALTH_HYGIENE,
  [COMPLAINT_CATEGORIES.OTHER]: DEPARTMENT_TYPES.GENERAL_CIVIC,
};

const getDepartmentByCategory = (category) => {
  return categoryDepartmentMap[category] || DEPARTMENT_TYPES.GENERAL_CIVIC;
};

module.exports = {
  getDepartmentByCategory,
  categoryDepartmentMap,
};